### ISSUE TITLE
Implemenmtation

### ISSUE THREAD

**Issue by gtbu** [manu37/tinymce5#2]
Instead of  
<!DOCTYPE html>
<html>
<head>
   <script src='https://cloud.tinymce.com/5/tinymce.min.js'>   
   <script>tinymce.init({ selector: #mytextarea });</script>
</head>
<body>
   <textarea id="mytextarea">Hello, World!</textarea>
</body>
</html>

Then, the API key using apiKey parameter:
<!DOCTYPE html>
<html>
<head>
   <script src='https://cloud.tinymce.com/5/tinymce.min.js?apiKey=xy...................8ghf'>   
   <script>tinymce.init({ selector: #mytextarea });</script>
</head>
<body>
   <textarea id="mytextarea">Hello, World!</textarea>
</body>
</html>

the plugin should allow to insert the Api-key in the cms - and the rest automatic - good luck !

**Comment by manu37** [comment]
I can't completely understand. Under Preferences>CDN you have the option to insert the CDN source including the API key. API key in the local option makes no sense.
![grafik](https://user-images.githubusercontent.com/712682/56862771-e2b13100-69ae-11e9-8e9d-6ca81a5648c4.png)
